[package]
name = "corestore"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.40"
random-access-storage = "5"
thiserror = "1.0.64"
random-access-memory = { version = "3.0.0" }
random-access-disk = { version = "3.0.1", default-features = false, features = ["sparse", "tokio"] }
tokio = { version = "1.40.0", features = ["macros", "test-util"] }
data-encoding = "2.6.0"
libsodium-sys-stable = "1.21.2"
signature = "2.2.0"
rand = "0.8.5"
derive_builder = "0.20.2"
futures-lite = "2.3.0"
futures = "0.3"
tokio-stream = { version = "0.1", features = ["sync"] }
delegate = "0.13.1"
hypercore_handshake = "0.6.0"

[dependencies.hypercore]
version = "0.17.0-alpha.1"
default-features = false
features = ["sparse", "replication"]

[dependencies.hypercore-protocol]
version = "0.7.2"

[dev-dependencies]
rusty_nodejs_repl = "0.2.1"
tempfile = "3.10.0"
tokio-util = { version = "0.7", features = ["compat"] }
uint24le_framing = "0.2.0"
